[mgr]
prepend_keymap = [
    { on = [ "<Esc>" ], run = "escape --all",              desc = "Exit visual mode, clear selected, or cancel search" },
    { on = [ "l" ],     run = "plugin smart-enter",        desc = "Enter the child directory, or open the file" },
    { on = [ "J" ],     run = "seek 5",                    desc = "" },
    { on = [ "K" ],     run = "seek -5",                   desc = "" },
    { on = [ "<C-`>"],  run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
    { on = [ "q" ],     run = "close",                     desc = "" },
    { on = [ "o" ],     run = "plugin open-with-cmd --args=block", desc = "Open with command in the terminal" },
    { on = [ "O" ],     run = "plugin open-with-cmd",      desc = "Open with command" },
]

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"
